azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/dag/DAGNode.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/dag/DAGraph.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/dag/Graph.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/dag/Node.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/dag/TaskGroup.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/dag/TaskGroupEntry.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/dag/TaskItem.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/model/implementation/CreatableUpdatableImpl.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/model/implementation/CreateUpdateTask.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/model/implementation/ExecutableImpl.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/model/implementation/ExecuteTask.java
azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/fluentcore/dag/CreatableUpdatableLCAImpl.java
azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/fluentcore/dag/DAGErrorTests.java
azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/fluentcore/dag/DAGFinalizeTests.java
azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/fluentcore/dag/DAGraphTest.java
azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/fluentcore/dag/DAGraphTests.java
azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/fluentcore/dag/PanCakeImpl.java
azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/fluentcore/dag/PastaImpl.java
azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/fluentcore/dag/PizzaImpl.java
azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/fluentcore/dag/ProxyTaskGroupTests.java

1. Code clean-up.
2. Support for adding post-run dependents: that enables execution of subset of dependents after the execution of dependency task group.
3. Support for InvocationContext
4. More test coverage (22 tests for DAG)

ProxyTaskGroup in DAG

---

azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayImpl.java
azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayInner.java

* Gateway zone support
* Ensuring gateway zone uniqueness & update java doc

Zone support for application gateway

---

azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/Region.java
azure-samples/src/main/java/com/microsoft/azure/management/compute/samples/CreateVirtualMachinesAsyncTrackingRelatedResources.java

(addressing issue https://github.com/Azure/azure-sdk-for-java/issues/1969)

Adding more government clouds

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/ResourceIdentityType.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineIdentity.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetIdentity.java

Updates based on [PR](https://github.com/Azure/azure-rest-api-specs/pull/2099).

Updating compute gen code with EMSI specific updates

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSet.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineImpl.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineMsiHelper.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetImpl.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetMsiHelper.java
azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineManagedServiceIdentityOperationsTests.java
azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetOperationsTests.java
azure-samples/src/main/java/com/microsoft/azure/management/compute/samples/ManageResourceFromMSIEnabledVirtualMachineBelongsToAADGroup.java
azure-samples/src/main/java/com/microsoft/azure/management/compute/samples/ManageStorageFromMSIEnabledVirtualMachine.java
azure-samples/src/main/java/com/microsoft/azure/management/compute/samples/ManageVirtualMachineFromMSIEnabledVirtualMachine.java
azure-samples/src/main/java/com/microsoft/azure/management/samples/Utils.java

Once we integrate new External (Explicit) Managed Service Identity, it is necessary to distinguish it from existing Local (Implicit) Managed Service Identity. This PR renames existing MSI methods in VM and VMSS to make it clear that those are Local (Implicit) MSI. PR adopts the terms [External, Local] agreed with AD team & portal.
<table>
<tr>
<th align=left>Area/Model</th>
<th align=left>In V1.4</th>
<th align=left>In V1.5</th>
<th align=left>Remarks</th>
<th align=left>Ref</th>
</tr>
<tr>
<td><code>VirtualMachine</code></td>
<td><code>.managedServiceIdentityTenantId()</code></td>
<td><code>.localManagedServiceIdentityTenantId()</code></td>
<td></td>
<td><a href="https://github.com/Azure/azure-libraries-for-java/pull/83">PR #83 </a></td>
</tr>
<tr>
<td><code>VirtualMachine</code></td> …

Be explicit about Local Managed Service Identity

---

azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/dag/TaskGroup.java
azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/fluentcore/dag/ProxyTaskGroupTests.java

This PR fixes the issue of NOT invoking “post run dependents” added via `beforeGroupInvoke` method of ROOT-task. The existing logic already handles the “post run dependents” added through `beforeGroupInvoke` methods in NON-ROOT tasks.

Fixing the issue of not invoking post run tasks added via beforeGroupInvoke of root task

---

swagger_to_sdk_config.json

Work with @daschult to bring automatic PR to Java.
Can be merged right away, cannot harm: this doesn't activate automatic PR system, it just allow me to test it live.
FYI @salameer

Basic SwaggerToSdk conf

---

azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/implementation/KubernetesClusterImpl.java

Related discussion here:
https://github.com/Azure/azure-libraries-for-java/issues/173

Fix getting AKS admin kube config

---

azure-mgmt-monitor/src/main/java/com/microsoft/azure/management/monitor/implementation/ActivityLogsImpl.java

Java fix for https://github.com/Azure/azure-libraries-for-net/issues/178

Monitor Activity log response filter fix

---

azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlElasticPoolImpl.java

Found this bug/typo during the CSharp implementation...

Sql elastic pools storage capacity is not properly set/updated

---

azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/SqlDatabase.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/SqlDatabaseAutomaticTuning.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/SqlServer.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/SqlServerAutomaticTuning.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlDatabaseAutomaticTuningImpl.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlDatabaseImpl.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlServerAutomaticTuningImpl.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlServerImpl.java
azure-mgmt-sql/src/test/java/com/microsoft/azure/management/sql/SqlServerOperationsTests.java
azure-mgmt-sql/src/test/resources/session-records/canChangeSqlServerAndDatabaseAutomaticTuning.json
azure-samples/src/test/java/com/microsoft/azure/management/samples/ContainerServiceTests.java
azure/src/test/java/com/microsoft/azure/management/AzureTests.java

Add support for SQL server and database automatic tunings.

Update for SQL and test recordings

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineExtensionImpl.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/models/implementation/IndependentChildResourceImpl.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/models/implementation/ResourceImpl.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/SqlDatabase.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/SqlDatabaseOperations.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/SqlElasticPool.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/SqlElasticPoolOperations.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlDatabaseImpl.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlElasticPoolImpl.java
azure-mgmt-sql/src/test/java/com/microsoft/azure/management/sql/SqlServerOperationsTests.java

Minor fixes when specifying withTags() for SQL databases and elastic pools.

SQL bug fixes - withTags() does not return the correct stage

---

azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/utils/ResourceManagerThrottlingInterceptor.java
azure-mgmt-sql/src/test/java/com/microsoft/azure/management/sql/SqlServerOperationsTests.java

Added a concurrent map instance to manage lock per each subscription.

Fix for throttling interceptor when multiple subscriptions are used.

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/ImageStorageProfile.java

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2652

[AutoPR compute/resource-manager] Make OSDisk in storage profile for VMImages optional

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/ImageStorageProfile.java

Adapting https://github.com/Azure/azure-rest-api-specs/pull/2652

reflecting the swagger change that makes Image::StorageProfile::OSDisk optional

---

azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/KeyPermissions.java
azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/StoragePermissions.java
azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/VaultPatchProperties.java
azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/VaultProperties.java
azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/implementation/VaultsInner.java

Created to accumulate context: keyvault/resource-manager

[AutoPR] keyvault/resource-manager

---

azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/BackupLongTermRetentionPoliciesInner.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/BackupLongTermRetentionPolicyInner.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/DatabaseOperationsInner.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlManagementClientImpl.java

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2615

[AutoPR sql/resource-manager] [DO NOT MERGE] Adding InstanceFailoverGroups 

---

azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/SubscriptionClientImpl.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/SubscriptionsInner.java

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2710

[AutoPR resources/resource-manager] Fix subscription paramter in SubscriptionClient

---

azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/BackupLongTermRetentionPoliciesInner.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/BackupLongTermRetentionPolicyInner.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/DatabaseOperationsInner.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlManagementClientImpl.java

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2711

[AutoPR sql/resource-manager] Removing instanceFailoverGroup from readme

---

azure-mgmt-cdn/src/main/java/com/microsoft/azure/management/cdn/implementation/CdnEndpointImpl.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetImpl.java
azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/implementation/MXRecordSetImpl.java
azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/PublicIPAddressImpl.java
azure-mgmt-servicebus/src/main/java/com/microsoft/azure/management/servicebus/implementation/TimeSpan.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlDatabaseImpl.java
azure-samples/src/main/java/com/microsoft/azure/management/samples/Utils.java
spotbugs-excludeFilter.xml

Fixes for issues found while running 'spotbugs'; with these changes in we should be able to pass a 'check' build.

Various bug fixes

---

azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/LongTermRetentionBackupsInner.java

Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2352

[AutoPR sql/resource-manager] Sql job agent

---

azure-samples/src/main/java/com/microsoft/azure/management/sql/samples/GettingSqlServerMetrics.java

Some small changes to how Monitor related metrics are retrieved/printed out

SQL: sample related changes

---

azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlServerAutomaticTuningImpl.java

bug fix; missing getInner() implementation which can cause the refresh() to fail.

SQL bug fix: missing getInner() implementation

---

azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlDatabaseOperationsImpl.java

bug fix: missing listBySqlServer() implementation...

SQL bug fix - missing implementation

---

api-specs.json
azure-mgmt-containerinstance/src/main/java/com/microsoft/azure/management/containerinstance/ContainerExecRequestTerminalSize.java
azure-mgmt-containerinstance/src/main/java/com/microsoft/azure/management/containerinstance/ContainerState.java
azure-mgmt-containerinstance/src/main/java/com/microsoft/azure/management/containerinstance/Event.java
azure-mgmt-containerinstance/src/main/java/com/microsoft/azure/management/containerinstance/Operation.java
azure-mgmt-containerinstance/src/main/java/com/microsoft/azure/management/containerinstance/OperationDisplay.java
azure-mgmt-containerinstance/src/main/java/com/microsoft/azure/management/containerinstance/implementation/ContainerExecResponseInner.java
azure-mgmt-containerinstance/src/main/java/com/microsoft/azure/management/containerinstance/implementation/ContainerInstanceManagementClientImpl.java
azure-mgmt-containerinstance/src/main/java/com/microsoft/azure/management/containerinstance/implementation/LogsInner.java
azure-samples/src/test/resources/session-records/testManageContainerInstanceWithAzureFileShareMount.json
azure-samples/src/test/resources/session-records/testManageContainerInstanceWithManualAzureFileShareMountCreation.json
azure-samples/src/test/resources/session-records/testManageContainerInstanceWithMultipleContainerImages.json
azure-samples/src/test/resources/session-records/testManageContainerInstanceZeroToOneAndOneToManyUsingContainerServiceOrchestrator.json
azure/src/test/resources/session-records/testContainerInstance.json

update ACI to package-2018-04 Swagger spec
update ACI test recordings

ACI: update to latest Swagger spec

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/DeploymentSlot.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/WebApp.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/DeploymentSlotImpl.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/KuduClient.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/WebAppImpl.java
azure-mgmt-appservice/src/test/java/com/microsoft/azure/management/appservice/WarDeployTests.java
azure-mgmt-appservice/src/test/resources/session-records/canDeployMultipleWars.json

Add more overloads to wardeploy

---

azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/CosmosDBAccountImpl.java

CosmosDB: fix for issue #307

---

azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/DeploymentImpl.java
azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/DeploymentsTests.java

fix for https://github.com/Azure/azure-libraries-for-net/issues/122

Fixed beginCreate bug for Deployment

---

azure-mgmt-powerbi/src/main/java/com/microsoft/azure/management/powerbi/Display.java
azure-mgmt-storage/src/main/java/com/microsoft/azure/management/storage/Restriction.java

Resolving issues related to cp1252 encoding accidentally being added into Java files, leading to JavaDoc issues.

Resolve encoding issues

---

azure-mgmt-trafficmanager/src/main/java/com/microsoft/azure/management/trafficmanager/implementation/TrafficManagerEndpointsImpl.java
azure-mgmt-trafficmanager/src/main/java/com/microsoft/azure/management/trafficmanager/implementation/TrafficManagerProfileImpl.java
azure/src/test/java/com/microsoft/azure/management/TestTrafficManager.java
azure/src/test/resources/session-records/testTrafficManager.json

Fix for https://github.com/Azure/azure-libraries-for-net/issues/121

Fixed Endpoint updates for traffic manager

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineImpl.java
azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineOperationsTests.java
azure-mgmt-compute/src/test/resources/session-records/canCreateVirtualMachine.json

Porting https://github.com/Azure/azure-libraries-for-net/pull/381 .

Adding licenseType parameter for virtual machine creation

---

azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGateway.java
azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ApplicationGatewayImpl.java
azure/src/test/java/com/microsoft/azure/management/TestApplicationGateway.java
azure/src/test/resources/session-records/testAppGatewaysInternetFacingComplex.json

Porting https://github.com/Azure/azure-libraries-for-net/pull/380 from C#.

enableHttp2 parameter for Application Gateway

---

azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/dag/DAGNode.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/dag/DAGraph.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/dag/Node.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/utils/Utils.java

This fixes issues with building this SDK under JDK 11 where the JavaDoc tooling is more stringent on HTML5 misuse.

Fix HTML5 javadoc issues

---

pom.xml

Reference: https://maven.apache.org/surefire/maven-surefire-plugin/examples/class-loading.html

Bumping up surefire version and setting useSystemClassLoader to false

---

azure-mgmt-locks/src/main/java/com/microsoft/azure/management/locks/implementation/ManagementLockImpl.java

Fix port for https://github.com/Azure/azure-libraries-for-net/issues/524

Fixed ResourceGroup management lock definition flow.

---

azure-mgmt-redis/src/main/java/com/microsoft/azure/management/redis/RedisCache.java
azure-mgmt-redis/src/main/java/com/microsoft/azure/management/redis/RedisCachePremium.java

Fix for https://github.com/Azure/azure-libraries-for-java/issues/678

Moved Reboot and Scheduled Updates functionality from Premium SKU to Base class. 

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/Disk.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/DiskImpl.java

Ref: https://github.com/Azure/azure-libraries-for-java/issues/675

Expose Disk.EncryptionSettings getter

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/WindowsVolumeEncryptionMonitorImpl.java

Fix for issue : https://github.com/Azure/azure-libraries-for-java/issues/712

Fix for : https://github.com/Azure/azure-libraries-for-java/issues/712

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/JavaVersion.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/RuntimeStack.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/WebContainer.java
azure-mgmt-appservice/src/test/java/com/microsoft/azure/management/appservice/LinuxWebAppsTests.java
azure-mgmt-appservice/src/test/java/com/microsoft/azure/management/appservice/WebAppConfigTests.java
azure-mgmt-appservice/src/test/resources/session-records/canCRUDLinuxJava11WebApp.json
azure-mgmt-appservice/src/test/resources/session-records/canCRUDLinuxWebApp.json
azure-mgmt-appservice/src/test/resources/session-records/canCRUDWebAppConfig.json
azure-mgmt-appservice/src/test/resources/session-records/canCRUDWebAppConfigJava11.json

Update java versions to support java 11

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetVMs.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetVMsImpl.java
azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetOperationsTests.java
azure-mgmt-compute/src/test/resources/session-records/canGetSingleVMSSInstance.json

https://github.com/Azure/azure-libraries-for-java/issues/746

Add getInstance API for VirtualMachineScaleestVMs.

---

README.md
notes/prepare-for-1.23.0.md

Hi @iscai-msft do we have any breaking change from ACI update? Didn't find any breaking changes from other commits. Thanks.

Update notes for java 1.23.0 release.

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FunctionApps.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FunctionEnvelope.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/FunctionAppsImpl.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/FunctionEnvelopeImpl.java
azure-mgmt-appservice/src/test/java/com/microsoft/azure/management/appservice/ZipDeployTests.java
azure-mgmt-appservice/src/test/resources/session-records/canZipDeployFunction.json

Fix for: https://github.com/Azure/azure-libraries-for-java/issues/729

Add function envelope.

---

azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/core/InterceptorManager.java
pom.xml

Fixes https://github.com/Azure/azure-sdk-for-java/issues/3939

Up runtime to 1.6.12 and okhttp to 3.14.2

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/RuntimeStack.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/WebContainer.java

RuntimeStack to latest.
WebContainer to add support for "java 8".

update AppService RuntimeStack and WebContainer

---

azure-mgmt-graph-rbac/src/main/java/com/microsoft/azure/management/graphrbac/implementation/RoleAssignmentImpl.java

Fix for https://github.com/Azure/azure-libraries-for-java/issues/808

Fix delay issue for role assignment during the testing.

---

azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/utils/ProviderRegistrationInterceptor.java

Proxy: support rest client with proxy in ProviderRegistrationInterceptor

---

azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewaySslCertificate.java
azure-mgmt-network/src/test/java/com/microsoft/azure/management/network/ApplicationGatewayTests.java
azure-mgmt-network/src/test/resources/session-records/canCreateApplicationGatewayWithSecret.json

fix: add app gateway ssl certificate in update definition

---

azure-samples/src/main/java/com/microsoft/azure/management/network/samples/ManageNetworkInterface.java
azure-samples/src/main/java/com/microsoft/azure/management/network/samples/ManageNetworkSecurityGroup.java
azure-samples/src/test/resources/session-records/testManageNetworkInterface.json

fix: randomize password and sshkey

---

azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/Region.java

https://github.com/Azure/azure-libraries-for-java/issues/874

middle east and africa region

---

azure-samples/src/main/resources/install_jva_mvn_git.sh

fix: use openjdk instead of oracle jdk in sample

---

azure-mgmt-monitor/src/main/java/com/microsoft/azure/management/monitor/MetricAlertRuleTimeAggregation.java

https://github.com/Azure/azure-libraries-for-net/pull/879

add enum Count to monitor metric alert

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/WebAppBase.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/WebAppBaseImpl.java
azure-mgmt-appservice/src/test/java/com/microsoft/azure/management/appservice/WebAppConfigTests.java
azure-mgmt-appservice/src/test/resources/session-records/canCRUDWebAppConfig.json

https://github.com/Azure/azure-libraries-for-java/issues/887

support minTlsVersion for web app

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FunctionRuntimeStack.java
azure-mgmt-appservice/src/test/java/com/microsoft/azure/management/appservice/FunctionAppsTests.java
azure-mgmt-appservice/src/test/resources/session-records/canCRUDLinuxFunctionApp.json
azure-mgmt-appservice/src/test/resources/session-records/canCRUDLinuxFunctionAppPremium.json

https://github.com/Azure/azure-libraries-for-java/issues/918

update linux java8 function image to latest v3

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AttributeCollection.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AttributeEnumCollection.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/PricingTier.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/RuntimeStack.java
azure-mgmt-appservice/src/test/java/com/microsoft/azure/management/appservice/UtilsTests.java

Fix https://github.com/Azure/azure-libraries-for-java/issues/748

add values() to RuntimeStack and PricingTier

---

gulpfile.js

Fix gulp generation for network.

---

azure-mgmt-eventhub/src/main/java/com/microsoft/azure/management/eventhub/AuthorizationRule.java
azure-mgmt-eventhub/src/main/java/com/microsoft/azure/management/eventhub/implementation/AuthorizationRuleBaseImpl.java
azure-mgmt-eventhub/src/test/java/com/microsoft/azure/management/eventhub/EventHubTests.java
azure-mgmt-eventhub/src/test/resources/session-records/canManageEventHubNamespaceAuthorizationRules.json

Fix https://github.com/Azure/azure-libraries-for-java/issues/971

support set both Listen and Send access

---

gulpfile.js

network, appservice etc. need `title`

vnext enh gulp

---

README.md

prepare-for-1.31.0 is already in https://github.com/Azure/azure-libraries-for-java/blob/master/notes/prepare-for-1.31.0.md

Release note 1.31.0

---

azure-mgmt-resources/src/main/java/com/azure/management/resources/fluentcore/utils/ProviderRegistrationPolicy.java
azure-mgmt-resources/src/main/java/com/azure/management/resources/fluentcore/utils/ResourceManagerThrottlingPolicy.java

All had been tested.
V1: https://github.com/Azure/azure-libraries-for-java/blob/bc5a8263bb43d6f03ef6cc74d99efe8f1c925b29/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/utils/ProviderRegistrationInterceptor.java
https://github.com/Azure/azure-libraries-for-java/blob/bc5a8263bb43d6f03ef6cc74d99efe8f1c925b29/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/utils/ResourceManagerThrottlingInterceptor.java
Issue: The ResourceManagerThrottling makes logging more and more, will test why

Migrate ProviderRegistrationPolicy and ResourceManagerThrottlingPolicy

---

azure-mgmt-resources/src/main/java/com/azure/management/AzureServiceClient.java
azure-mgmt-resources/src/main/java/com/azure/management/resources/fluentcore/utils/DelayProvider.java
azure-mgmt-resources/src/main/java/com/azure/management/resources/fluentcore/utils/SdkContext.java
azure-mgmt-resources/src/test/java/com/azure/management/resources/core/TestDelayProvider.java

Not good enough for 0 delay, which need fix on the underlying framework.

Fix test case timeout.

---

gulpfile.js

1. autorest v3 released
2. generator refactored to have 2 parts, namer + generator

vnext gulp

---

.github/CODEOWNERS
azure-samples/samples.json

Update sample/repo owner.

---

azure-mgmt-appservice/pom.xml
azure-mgmt-batch/pom.xml
azure-mgmt-batchai/pom.xml
azure-mgmt-compute/pom.xml
azure-mgmt-containerinstance/pom.xml
azure-mgmt-containerregistry/pom.xml
azure-mgmt-containerservice/pom.xml
azure-mgmt-cosmosdb/pom.xml
azure-mgmt-datalake-analytics/pom.xml
azure-mgmt-datalake-store/pom.xml
azure-mgmt-dns/pom.xml
azure-mgmt-eventhub/pom.xml
azure-mgmt-graph-rbac/pom.xml
azure-mgmt-keyvault/pom.xml
azure-mgmt-monitor/pom.xml
azure-mgmt-msi/pom.xml
azure-mgmt-network/pom.xml
azure-mgmt-redis/pom.xml
azure-mgmt-servicebus/pom.xml
azure-mgmt-sql/pom.xml
azure-mgmt-storage/pom.xml
azure-mgmt-trafficmanager/pom.xml
azure-samples/pom.xml
azure/pom.xml

Fix https://github.com/Azure/azure-libraries-for-java/issues/1094
profile id is `azure-mgmt-sdk-test-jar`

move test-jar to profile

---

.azure-pipelines/fluentJavaMgmt.yml

Only trigger CI in master pr

---

pom.xml

Fix https://github.com/Azure/azure-libraries-for-java/issues/1088

upgrade keyvault client libs

---

azure-samples/src/test/resources/session-records/testManageWebAppStorageAccountConnection.json

still better to have post job to do this automatically.

vnext clean secret

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/FunctionAppImpl.java

Fix https://github.com/Azure/azure-libraries-for-java/issues/1154
Backport from track2

update getMasterKey rest api

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FunctionApp.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/FunctionAppImpl.java

Fix https://github.com/Azure/azure-libraries-for-java/issues/1155
Sample code
```
Map<String, String> payload = new HashMap<>();
payload.put("input", "testAAA");
functionApp.triggerFunction("QueueTrigger1", payload);
```

support triggerFunction

---

azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/PublicIPAddressImpl.java

Fix [Azure/azure-sdk-for-java#9852](https://github.com/Azure/azure-sdk-for-java/issues/9852)

Network: fix NPE in public ip address

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineExtensionsImpl.java

fix https://github.com/Azure/azure-sdk-for-java/issues/1967

fix: vm extension npe exception

---

AUTH.md

Sample: fix link to sample of auth file creation

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachinePriorityTypes.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSet.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineImpl.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetImpl.java

Fix: [Azure/azure-sdk-for-java#10706](https://github.com/Azure/azure-sdk-for-java/issues/10706)

Compute: support to set eviction policy in vmss

---

azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/utils/ResourceManagerThrottlingInterceptor.java

try to fix
https://github.com/Azure/azure-sdk-for-java/issues/6588

feat: try to close response in 429

---

azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkUsageUnit.java

Align: [Azure/azure-sdk-for-java#10770](https://github.com/Azure/azure-sdk-for-java/pull/10770)

Network: fix typo in NetworkUsageUnit

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/ComputeSku.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/ComputeSkus.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/Disk.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/DiskVolumeEncryptionMonitor.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/Disks.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/Galleries.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/Gallery.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/GalleryImage.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/GalleryImageVersion.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/GalleryImageVersions.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/GalleryImages.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/Snapshots.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineCustomImage.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSet.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetVM.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetVMs.java

Compute: remove beta annotations

---

azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/ResourceManager.java
azure/src/main/java/com/microsoft/azure/management/Azure.java

https://github.com/Azure/azure-libraries-for-java/issues/1193

feat: expose subs and tenants from resource manager and azure

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/FunctionAppImpl.java
azure-mgmt-appservice/src/test/java/com/microsoft/azure/management/appservice/FunctionAppsTests.java
azure-mgmt-containerinstance/src/main/java/com/microsoft/azure/management/containerinstance/implementation/ContainerGroupImpl.java
azure-mgmt-eventhub/src/main/java/com/microsoft/azure/management/eventhub/implementation/EventHubImpl.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/utils/Utils.java
azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlDatabaseExportRequestImpl.java

Fix https://github.com/Azure/azure-libraries-for-java/issues/1200

EndpointSuffix is needed for non Global

---

azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/models/implementation/ResourceImpl.java

I don't want these tags in my application output

Remove System.out.println from ResourceImpl#withTag

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSet.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineImpl.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetImpl.java

Fix: [Azure/azure-sdk-for-java#11912](https://github.com/Azure/azure-sdk-for-java/issues/11912)

Compute: support specialized gallery image version

---

azure-mgmt-monitor/src/main/java/com/microsoft/azure/management/monitor/implementation/MetricDefinitionsImpl.java

fix https://github.com/Azure/azure-sdk-for-java/issues/13316

NP protection

---

azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/DeploymentOperation.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/DeploymentOperationImpl.java

Support: [Azure/azure-libraries-for-java#772](https://github.com/Azure/azure-libraries-for-java/issues/772)

Resources: support provisioningOperation

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/AvailabilitySetImpl.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineImpl.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetImpl.java

Fix https://github.com/Azure/azure-libraries-for-java/issues/1247

fix npe in compute

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FunctionDeploymentSlot.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/DeploymentSlotsImpl.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/FunctionDeploymentSlotImpl.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/FunctionDeploymentSlotsImpl.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/WebAppBaseImpl.java

@Flanker32 
3 issues.
1. service not accept the empty siteConfig in PUT when create new slot
2. PATCH not working, had to use PUT
3. SDK error in sending name in request (name from service is e.g. `java-funcapp-36626c/java-slot-43411876b`, which is `parent/slot`).

fix function app slot

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/DeploymentSlot.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/DeploymentSlotBase.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FunctionDeploymentSlot.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/DeploymentSlotBaseImpl.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/FunctionDeploymentSlotImpl.java
azure-mgmt-appservice/src/test/java/com/microsoft/azure/management/appservice/FunctionAppsTests.java
azure-mgmt-appservice/src/test/java/com/microsoft/azure/management/appservice/FunctionDeploymentSlotsTests.java
azure-mgmt-appservice/src/test/resources/session-records/canCRUDFunctionSlots.json

Fix https://github.com/Azure/azure-libraries-for-java/issues/1263
@Flanker32 
I've added a shared Update flow for dockerimage (via `DeploymentSlotBase` interface).
Create flow is not added, and it likely not able to be shared.
Let me know your feedback.

appservice slot update support dockerimage

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/FunctionAppImpl.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/AzureConfigurable.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/implementation/AzureConfigurableImpl.java
azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/core/TestBase.java
pom.xml

fix https://github.com/Azure/azure-libraries-for-java/issues/1197
Code sample
```
Azure azure = Azure.configure()
.withProtocols(Arrays.asList(Protocol.HTTP_1_1))
...
```

support OkHttp protocols

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/DeploymentSlotsImpl.java
azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/FunctionDeploymentSlotsImpl.java

fix https://github.com/Azure/azure-libraries-for-java/issues/1278
@Flanker32

fix npe on functionApp.deploymentSlots().getByName

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/RuntimeStack.java

Fix https://github.com/Azure/azure-libraries-for-java/issues/1281

support JBOSS EAP

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/GalleriesImpl.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/GalleryImageVersionsImpl.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/GalleryImagesImpl.java

Fix: [Azure/azure-sdk-for-java#15097](https://github.com/Azure/azure-sdk-for-java/issues/15097)

fix NPE when wrapping model for gallery and related

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/KuduClient.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/utils/ProviderRegistrationInterceptor.java

Make a `RestException` when fail to deploy.

improve error handling for OneDeploy/warDeploy/zipDeploy

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/FunctionAppImpl.java

fix https://github.com/Azure/azure-libraries-for-java/issues/1306

remove not allowed char in storage account name

---

azure-mgmt-appservice/pom.xml
azure-mgmt-batch/pom.xml
azure-mgmt-batchai/pom.xml
azure-mgmt-cdn/pom.xml
azure-mgmt-compute/pom.xml
azure-mgmt-containerinstance/pom.xml
azure-mgmt-containerregistry/pom.xml
azure-mgmt-containerservice/pom.xml
azure-mgmt-cosmosdb/pom.xml
azure-mgmt-datalake-analytics/pom.xml
azure-mgmt-datalake-store/pom.xml
azure-mgmt-dns/pom.xml
azure-mgmt-eventhub/pom.xml
azure-mgmt-graph-rbac/pom.xml
azure-mgmt-keyvault/pom.xml
azure-mgmt-locks/pom.xml
azure-mgmt-monitor/pom.xml
azure-mgmt-msi/pom.xml
azure-mgmt-network/pom.xml
azure-mgmt-redis/pom.xml
azure-mgmt-resources/pom.xml
azure-mgmt-search/pom.xml
azure-mgmt-servicebus/pom.xml
azure-mgmt-sql/pom.xml
azure-mgmt-storage/pom.xml
azure-mgmt-trafficmanager/pom.xml
azure-samples/pom.xml
azure/pom.xml
azure/src/main/java/com/microsoft/azure/management/Azure.java
pom.xml

Also add the redirection on javadoc of `Azure` class.

update docs to point to new mgmt libs

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetImpl.java

Compute: fix vmss npe issue

---

.azure-pipelines/fluentJavaMgmt.yml

To check if the pipeline extension gets upgraded new version now.

CredScan: explicit latest version

---

azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/VirtualNetworkGatewayConnectionImpl.java

Fix: [Azure/azure-sdk-for-java#18083](https://github.com/Azure/azure-sdk-for-java/issues/18083)

Network: fix VirtualNetworkGatewayConnection shared key update

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineImpl.java
azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/implementation/VirtualMachineUpdateTests.java
azure-mgmt-compute/src/test/resources/session-records/canEnableDiagnosticsExtension.json
azure-mgmt-compute/src/test/resources/session-records/canHandleExtensionReference.json
azure-mgmt-compute/src/test/resources/session-records/canInstallUninstallCustomExtension.json
azure-mgmt-compute/src/test/resources/session-records/canResetPasswordUsingVMAccessExtension.json
azure-mgmt-compute/src/test/resources/session-records/testVirtualMachineUpdate.json
azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/core/TestUtilities.java
azure-samples/src/test/resources/session-records/testManageVirtualMachineExtension.json

fix https://github.com/Azure/azure-libraries-for-java/issues/1348

Avoid PATCH during VM update flow, when VM itself is not modified

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/LinuxVMDiskEncryptionConfiguration.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineEncryption.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineEncryptionConfiguration.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WindowsVMDiskEncryptionConfiguration.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineEncryptionImpl.java
azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineEncryptionOperationsTests.java
azure-mgmt-compute/src/test/resources/session-records/canEncryptVirtualMachine.json
azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/core/TestBase.java

Fix https://github.com/Azure/azure-libraries-for-java/issues/1353

Bug fix on compute disk encrypt

---

azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/ApplicationGatewayFirewallExclusion.java

Network: remove property validation for ApplicationGatewayFirewallExclusion

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/LinuxVMDiskEncryptionConfiguration.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/WindowsVMDiskEncryptionConfiguration.java

bug fix on incorrect constructor

---

azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlDatabaseOperationsImpl.java
settings.xml

fix https://github.com/Azure/azure-sdk-for-java/issues/19055

NPE protection in sql server

---

azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Deployment.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/Context.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/dag/TaskGroup.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/model/implementation/CreatableUpdatableImpl.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/model/implementation/CreateUpdateTask.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/DeploymentImpl.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/DeploymentsInner.java
azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/DeploymentsTests.java
azure-mgmt-resources/src/test/resources/session-records/canDeployVirtualNetworkWithContext.json

Only for `create` and `beginCreate` on `Deployment`.

Proof of concept, add x-ms-correlation-request-id to Deployment

---

azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/RuntimeStack.java

Fix https://github.com/Azure/azure-libraries-for-java/issues/1298

add jboss eap 7 to webapp runtimestack

---

azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/TagOperations.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/TagResource.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/ResourceManager.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/TagOperationsImpl.java
azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/TagResourceImpl.java
azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/TagsTests.java
azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/implementation/TypeSerializationTests.java
azure-mgmt-resources/src/test/resources/session-records/canUpdateTag.json
azure/src/main/java/com/microsoft/azure/management/Azure.java

Mitigate
https://github.com/Azure/autorest-clientruntime-for-java/issues/663
https://github.com/Azure/azure-sdk-for-java/issues/20150
Mirror https://github.com/Azure/azure-sdk-for-java/pull/20156

mitigate bug related to dot and flatten from azure-client-runtime

---

azure-mgmt-graph-rbac/src/main/java/com/microsoft/azure/management/graphrbac/implementation/ActiveDirectoryApplicationImpl.java

Fix https://github.com/Azure/azure-sdk-for-java/issues/20161

fix update flow in graph-rbac

---

azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/KubernetesCluster.java
azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/KubernetesClusterAgentPool.java
azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/implementation/KubernetesClusterAgentPoolImpl.java
azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/implementation/KubernetesClusterImpl.java
azure-mgmt-containerservice/src/test/java/com/microsoft/azure/management/containerservice/KubernetesClustersTests.java
azure-mgmt-containerservice/src/test/resources/session-records/canCRUDKubernetesCluster.json
azure-samples/src/main/java/com/microsoft/azure/management/kubernetescluster/samples/ManageKubernetesCluster.java
azure-samples/src/main/java/com/microsoft/azure/management/kubernetescluster/samples/ManagedKubernetesClusterWithAdvancedNetworking.java
azure/src/test/java/com/microsoft/azure/management/TestKubernetesCluster.java

Fix https://github.com/Azure/azure-libraries-for-java/issues/1387

support add/update AKS agent pool

---

azure-mgmt-batchai/pom.xml
azure-mgmt-compute/pom.xml
azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/ComputeManagementTest.java
azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/SharedGalleryImageTests.java
azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/SshShell.java
azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineCustomImageOperationsTest.java
azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineManagedDiskOperationsTests.java
azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetManagedDiskOperationsTests.java
azure-mgmt-compute/src/test/resources/session-records/canCreateImageFromNativeVhd.json
azure-mgmt-compute/src/test/resources/session-records/canCreateVirtualMachineFromCustomImageWithManagedDisks.json
azure-mgmt-compute/src/test/resources/session-records/canCreateVirtualMachineScaleSetFromCustomImageWithManagedDisk.json
azure-mgmt-eventhub/pom.xml
azure-samples/pom.xml
azure-samples/src/main/java/com/microsoft/azure/management/compute/samples/CreateVirtualMachineUsingCustomImageFromVHD.java
azure-samples/src/main/java/com/microsoft/azure/management/compute/samples/CreateVirtualMachineUsingCustomImageFromVM.java
azure-samples/src/main/java/com/microsoft/azure/management/compute/samples/CreateVirtualMachinesUsingCustomImageOrSpecializedVHD.java
azure-samples/src/main/java/com/microsoft/azure/management/compute/samples/ManageManagedDisks.java
azure-samples/src/main/java/com/microsoft/azure/management/samples/SSHShell.java
azure-samples/src/test/resources/session-records/testCreateVirtualMachineUsingCustomImageFromVHD.json
azure-samples/src/test/resources/session-records/testCreateVirtualMachinesUsingCustomImageOrSpecializedVHD.json
azure-samples/src/test/resources/session-records/testManageManagedDisks.json

remove expect4j for it has repo setting that get banned by maven 3.8.1

remove expect4j

---

azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VMSSPatchPayload.java
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineImpl.java

fix https://github.com/Azure/azure-libraries-for-java/issues/632

vm, do not update plan in VM update

---

.github/CODEOWNERS
azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineImpl.java

Port from track2 https://github.com/Azure/azure-sdk-for-java/pull/24154

compute VM, fix possible NPE
