Azure/azure-libraries-for-java

- azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/KubernetesCluster.java
Can't specify all the options when selecting .withVersion()
> Container services (AKS) - Fix for #1989

- azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
- azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSet.java
- azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineImpl.java
- azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetImpl.java
- azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineManagedServiceIdentityOperationsTests.java
- azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetOperationsTests.java
- azure-samples/src/main/java/com/microsoft/azure/management/compute/samples/ManageResourceFromMSIEnabledVirtualMachineBelongsToAADGroup.java
- azure-samples/src/main/java/com/microsoft/azure/management/compute/samples/ManageStorageFromMSIEnabledVirtualMachine.java
- azure-samples/src/main/java/com/microsoft/azure/management/compute/samples/ManageVirtualMachineFromMSIEnabledVirtualMachine.java
- azure-samples/src/main/java/com/microsoft/azure/management/samples/Utils.java
Once we integrate new User Assigned Managed Service Identity, it is necessary to distinguish it from existing System Assigned Managed Service Identity. This PR renames existing MSI methods in VM and VMSS to make it clear that those areSystem Assigned MSI. PR adopts the terms [User Assigned, SystemAssigned] agreed with AD team & portal.
<table>
<tr>
<th align=left>Area/Model</th>SystemAssigned
<th align=left>In V1.4</th>
<th align=left>In V1.5</th>
<th align=left>Remarks</th>
<th align=left>Ref</th>
</tr>
<tr>
<td><code>VirtualMachine</code></td>
<td><code>.managedServiceIdentityTenantId()</code></td>
<td><code>.systemAssignedManagedServiceIdentityTenantId()</code></td>
<td></td>
<td><a href="https://github.com/Azure/azure-libraries-for-java/pull/83">PR #83 </a><br/><a …
> Renaming Local MSI to SystemAssigned MSI

- azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/ApplicationImpl.java
- azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/ApplicationPackageImpl.java
- azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/ApplicationPackagesImpl.java
- azure-mgmt-batch/src/main/java/com/microsoft/azure/management/batch/implementation/ApplicationsImpl.java
- azure-mgmt-cdn/src/main/java/com/microsoft/azure/management/cdn/implementation/CdnEndpointImpl.java
- azure-mgmt-cdn/src/main/java/com/microsoft/azure/management/cdn/implementation/CdnEndpointsImpl.java
- azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineExtensionImpl.java
- azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineExtensionsImpl.java
- azure-mgmt-containerregistry/src/main/java/com/microsoft/azure/management/containerregistry/implementation/WebhookImpl.java
- azure-mgmt-containerregistry/src/main/java/com/microsoft/azure/management/containerregistry/implementation/WebhooksImpl.java
- azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/implementation/DnsRecordSetImpl.java
- azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/implementation/DnsRecordSetsImpl.java
- azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/collection/implementation/ExternalChildResourceCollectionImpl.java
- azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/collection/implementation/ExternalChildResourcesCachedImpl.java
- azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/collection/implementation/ExternalChildResourcesNonCachedImpl.java
- azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/models/implementation/ExternalChildResourceImpl.java
- azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/childresource/ExternalChildResourceTests.java
- azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/childresource/PulletImpl.java
- azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/childresource/PulletsImpl.java
- azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/childresource/SchoolsImpl.java
- azure-mgmt-trafficmanager/src/main/java/com/microsoft/azure/management/trafficmanager/implementation/TrafficManagerEndpointImpl.java
- azure-mgmt-trafficmanager/src/main/java/com/microsoft/azure/management/trafficmanager/implementation/TrafficManagerEndpointsImpl.java
@milismsft this PR should address the new design requirement you wanted to support in SQL.
PR enables following two new ** NEW SUPPORT**:
[1]. Enable external child resources to add dependencies just like any other top-level resources.
[2]. Enable external child resources to be defined independently in addition to currently supported inline definition. 
-- Example --
Let’s say we have a top level resource `School` and it’s collection `Schools`. A `School` instance has two external child resources `Teachers` (with `Teacher` as collection item type) and `Students` (with `Student` as collection item type).
**[CURRENT SUPPORT]** The current external child resource design allows inline definition of external child resource along with parent definition/update:
```java
schools() …
```
> Support for external child resource independent definition & update and dependencies for external child resource

- azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/StorageAccountTypes.java
Adding `StandardSSD_LRS` enum value to `StorageAccountTypes` in this [commit](https://github.com/Azure/azure-libraries-for-java/pull/145/commits/98a74a80371fd3ea65614c410865ea3132dbde7e). Opened an [issue](https://github.com/Azure/azure-rest-api-specs/issues/2343)  in rest api spec. For now this need to be manually patched otherwise deserialization of the values *will fail* and clients will start seeing exceptions.
> Adding missing StandardSSD_LRS enum-value to StorageAccountTypes

- azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/StorageAccountTypes.java
Related to the issue described in this [PR](https://github.com/Azure/azure-libraries-for-java/pull/145)
While testing with different subscriptions, found that there is one more enum value `Standard_ZRS`, this PR add that value as well. Update the [issue](https://github.com/Azure/azure-rest-api-specs/issues/2343) in the api spec.
> Adding StorageAccountTypes::Standard_ZRS

- gulpfile.js
Fixes a breaking config change that was introduced in azure-rest-api-specs.
It seems to me that while AutoRest config which affects the meaning of the generated code, like `input-file` and `title` may belong in azure-rest-api-specs, but stuff like `output-folder` and `clear-output-folder` is project-specific and shouldn't necessarily come from azure-rest-api-specs.
I'm not invested in this working any particular way so feel free to make any changes to the gulpfile in here @daschult as long as the code generation works :)
> Use gulpfile-specified output folder

- gulpfile.js
"current" branch was recently deleted from azure-rest-api-specs and "master" instead contains the up to date API specs. This changes the URL in gulpfile.js to look up AutoRest config files under the master branch.
> Use master azure-rest-api-specs branch since current branch no longer exists

- azure-samples/src/main/java/com/microsoft/azure/management/batchai/samples/ManageBatchAI.java
Fixes issue as discussed in https://github.com/Azure/azure-libraries-for-java/issues/171#issuecomment-367133811
> Fix use of ampersand characters in JavaDoc by replacing with &amp;

- pom.xml
- spotbugs-excludeFilter.xml
- spotbugs-includeFilter.xml
Commands to use:
- mvn spotbugs:spotbugs - generates an XML report under the target of the child project
- mvn spotbugs:check - fails the build if bugs are found
- mvn spotbugs:gui - opens an UI app to check the bugs found
Currently only detect and fail if CORRECTNESS issues were found.
> Add spotbugs plugin, include only and exclude filter list

- azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/KeyPermissions.java
- azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/StoragePermissions.java
- azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/VaultPatchProperties.java
- azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/VaultProperties.java
- azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/implementation/VaultsInner.java
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2650
> [AutoPR keyvault/resource-manager] Add node config to keyvault for Swagger to SDK

- azure-mgmt-containerinstance/src/main/java/com/microsoft/azure/management/containerinstance/ContainerExecRequestTerminalSize.java
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2651
> [AutoPR containerinstance/resource-manager] Fixing Error in Naming Convention for Rows and Cols in Terminal Size

- azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/SubscriptionClientImpl.java
- azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/SubscriptionsInner.java
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2670
> [AutoPR resources/resource-manager] Move subscriptionId to global

- azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/DeploymentExtendedInner.java
- azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/PolicyDefinitionInner.java
- azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/TagDetailsInner.java
- azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/TagValueInner.java
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2678
> [AutoPR resources/resource-manager] Fix some of the error in ARM swagger spec

- azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ExpressRouteCrossConnectionPeeringsInner.java
- azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ExpressRouteCrossConnectionsInner.java
- azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/NetworkManagementClientImpl.java
Created to sync https://github.com/Azure/azure-rest-api-specs/pull/2720
> [AutoPR network/resource-manager] Fixed operationIds for non-CRUD operations in ExpressRouteCrossConnections

- azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/CosmosDBAccount.java
- azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/CosmosDBAccountImpl.java
- azure-mgmt-cosmosdb/src/test/java/com/microsoft/azure/management/cosmosdb/CosmosDBTests.java
- azure-mgmt-cosmosdb/src/test/resources/session-records/CanCreateCosmosDbAzureTableAccount.json
- azure-mgmt-cosmosdb/src/test/resources/session-records/CanCreateCosmosDbCassandraAccount.json
- azure-mgmt-cosmosdb/src/test/resources/session-records/CanCreateCosmosDbMongoDBAccount.json
- azure-mgmt-cosmosdb/src/test/resources/session-records/CanCreateCosmosDbSqlAccount.json
Add missing implementations to create Cassandra, Azure Table and Gremlin data model CosmosDB accounts.
> CosmosDB: Add missing implementations for creating other data models

- README.md
- notes/prepare-for-1.10.0.md
> Readme 1.10

- azure-mgmt-storage/src/main/java/com/microsoft/azure/management/storage/StorageAccount.java
fix for https://github.com/Azure/azure-libraries-for-net/issues/316
> Added storage method annotation to Fluent flow

- azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/DeploymentSlotBaseImpl.java
Pass publishing profile options when get publishing profile in deployment slot, for issue #955 
Refers [AppServiceBaseImpl](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/AppServiceBaseImpl.java#L190)
> Pass publishing profile options when get publishing profile in deployment slot

- azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/FunctionAppsImpl.java
- azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/WebAppsImpl.java
Fix https://github.com/Azure/azure-libraries-for-java/issues/953
`Observable.just(null)` probably is not a good idea. But anyway `null` is what returned from `Inner.getByResourceGroupAsync()`.
> fix NoSuchElementException in WebApp and FunctionApp

- azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/utils/AuxiliaryCredentialsInterceptor.java
by https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/authenticate-multi-tenant
> fix: authorization-auxiliary use "," to separate instead of ";"

- api-specs.json
- gulpfile.js
change option to track1-naming (e.g. withName), now default is track2 style (e.g. setName)
also latest autorest support `tag`
> vnext update gulp

- azure-mgmt-cosmosdb/pom.xml
- pom.xml
Bump jackson-databind from 2.9.4 to 2.9.10.3  dependencies
Bump checkstyle from 8.24 to 8.29 in /azure-mgmt-cosmosdb  dependencies
> fix security

- azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/Secret.java
- azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/implementation/KeyVaultFutures.java
- azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/implementation/SecretImpl.java
> KeyVault: filter out disabled secret while listing secret versions

- azure-mgmt-graph-rbac/src/main/java/com/microsoft/azure/management/graphrbac/implementation/ActiveDirectoryUserImpl.java
I tried to update an AAD user password using the following code
```
ActiveDirectoryUser user = activeDirectoryUser.update()
.withPassword(new String(password, StandardCharsets.UTF_8))
.withPromptToChangePasswordOnLogin(false)
.withAccountEnabled(true)
.apply();
```
and the password was not updated.
It seems that the PATCH request to Microsoft Graph API used to update the user password is missing the password field. 
This was the request body
`{"accountEnabled":true,"displayName":"florin-test Service Account"}`
This is the new request body
`{"accountEnabled":true,"displayName":"florin-test Service Account","passwordProfile":{"password":"new-pass","forceChangePasswordNextLogin":false}}`
I also have an Azure Ticket: **120031822000981**
> Fix for update Azure Active Directory account password

- azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/implementation/KubernetesClustersImpl.java
- azure-mgmt-containerservice/src/test/resources/session-records/canCRUDKubernetesCluster.json
- azure/src/test/java/com/microsoft/azure/management/AzureTests.java
- azure/src/test/java/com/microsoft/azure/management/TestKubernetesCluster.java
- azure/src/test/resources/session-records/testKubernetesCluster.json
per AKS team's ask, deprecate getAccessProfile API, instead of using ListClusterAdminCredentials / ListClusterUserCredentials 
```
From: Ruchika Gupta <rucgupt@microsoft.com>
Sent: Wednesday, March 18, 2020 7:17
To: Tanyi Chen <Tanyi.Chen@microsoft.com>
Cc: Jorge Palma <Jorge.Palma@microsoft.com>
Subject: Update azure-libraries-for-net repo to not use AKS GetAccessProfile API 
Hi Tanyi,
I’m Ruchika, an engineer on Azure Kubernetes Service team. I got your contact from the azure-libraries-for-net github repo releases, please redirect me if you’re not the right contact. 
We are in the process to deprecate GetAccessProfile API and are reaching out to partners using this API. We noticed that this repo is using GetAccessProfile API to set the cluster user and cluster admin kubeconfigs …
```
> feat: deprecate getAccessProfile api

- azure-mgmt-resources/pom.xml
- azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/utils/ResourceManagerThrottlingInterceptor.java
- azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/fluentcore/utils/ResourceManagerThrottlingInterceptorTests.java
fix https://github.com/Azure/azure-libraries-for-java/issues/1251
ratelimit could have different limit on write/read/delete
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/request-limits-and-throttling
Hence it likely helps to separate them (to avoid the case that a throttle write blocks a subsequent delete or read).
Pending mock server test.
> throttle base on subscriptionId and request method

- azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/utils/ReturnRequestIdHeaderInterceptor.java
to request server put x-ms-client-request-id in response
Sample usage:
```
Azure azure = Azure.configure()
.withInterceptor(new ReturnRequestIdHeaderInterceptor())
.authenticate(...)
...
```
Header can be accessed in Exception.
```
exception.response().headers().get("x-ms-client-request-id")
```
> ReturnRequestIdHeaderInterceptor

- azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/WebAppBase.java
- azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/KuduClient.java
- azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/WebAppBaseImpl.java
fix https://github.com/Azure/azure-libraries-for-java/issues/1314
> webapp support api/settings from Kudu

- azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
- azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineImpl.java
Fix https://github.com/Azure/azure-libraries-for-java/issues/1346
> support withBootDiagnosticsOnManagedStorageAccount

- azure-mgmt-eventhub/pom.xml
- azure-mgmt-trafficmanager/pom.xml
- pom.xml
commons-io is for security alert. 2.7 requires Java8, but I guess it is OK as in test.
> upgrade dependencies

- README.md
- azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineOperationsTests.java
output should look like this in `Schedulers.io()`
```
time to call ends: 62.8645
time to delete success: 23231.8163
```
> compute, vm, add test for deleteByIdAsync with forceDelection
